//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rabbit_event_list {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class rabbitsettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static rabbitsettings defaultInstance = ((rabbitsettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new rabbitsettings())));
        
        public static rabbitsettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double winpositionX {
            get {
                return ((double)(this["winpositionX"]));
            }
            set {
                this["winpositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double winpositionY {
            get {
                return ((double)(this["winpositionY"]));
            }
            set {
                this["winpositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eventlistjson {
            get {
                return ((string)(this["eventlistjson"]));
            }
            set {
                this["eventlistjson"] = value;
            }
        }
    }
}
